### PR TITLE
Moving post analysis scripts to new folder & removing old post qFit scripts

### PR DESCRIPTION
**Pull request by stephaniewankowicz**
After much futzing, I think the best folder structure should be:

qfit-3.0/src/qfit/: base scripts
qfit-3.0/src/post_analysis_scripts: scripts based on qFit package but not needed to run qFit itself

qfit-3.0/scripts: pre/post refinement scripts, bulk solvent, ect. These scripts do not call qFit to run. 

Open for feedback on this structure.

### CODE REVIEW

**Comment by blake-riley** [comment]
What are your thoughts on:
- /src/qfit: qfit package
- /scripts/pre: things to be run before
- /scripts/post: things to be run after

I'm not convinced we need a distinction between things that require qFit and things that don't. Imo, the user shouldn't need to be made aware of such a distinction.
Also, I think it's reasonably safe to assume that if the user is accessing these scripts, they've already installed qFit.

**Comment by stephaniewanko** [comment]
I like that. Should we make the shell scripts CLI as well?

**Comment by blake-riley** [comment]
Yes. Things in the scripts folder should have 755 permissions. Especially if we're going to make them available through the setup.py.

**Comment by stephaniewankowicz** [comment]
This PR is deleting the following scripts:
check_qfit_run.sh
post_refine_phenix_restraints.csh 
post_refine_phenix_single.csh
qfit_complete_parser.py
qfit_complete_wrapper.sh
run_protein.py

**Comment by stephaniewankowicz** [comment]
For find_largest_ligand, please keep moving_scripts version. I can't seem to resolve the conflict without merging.

**Comment by blake-riley** [comment]
Hey Stephanie, why are the scripts in src/scripts, and not just in scripts like was agreed to https://github.com/ExcitedStates/qfit-3.0/pull/84#issuecomment-658304726 ?

Your changes to setup.py (probably removing `packages = find_packages('src')` ?) seems to have broken the package structure of qfit. **None of the CI tests complete**, they can't run `qfit_protein --help`, and it's because they can't find qfit.Structure.

I should probably explain how these pre/post scripts fit into the setuptools model: these post/pre scripts are being distributed with the package, but they're not part of the qFit source itself (they shouldn't be accessible if someone types `import qfit`), especially not the .sh files.
As such, they shouldn't be in src/, nor should they be listed in the packages argument to setup.

Also, following from this, they don't fit in `entry_points={'console_scripts':[...]}`.
I strongly recommend using
```
setup(
   ...
   scripts=[
        'name_of_script.py',
        'qfit_final_refine_xray.sh',
        ...,
   ],
   ...
)
```
instead.

**Comment by blake-riley** [comment]
Also, you shouldn't merge dev back into your branch, for a PR that will be merged into dev.
This goes against the idea of separating independent lines of development.

**Comment by stephaniewankowicz** [comment]
this works on my local branch on my computer (qfit_protein, qfit_ligand). I was not able to get the structure of /scripts/___ to work in the setup script. If we do what you suggested then we need the package to start ABVOE src, which then gets in the way with the tests, ect. Which is why I stated earlier (see comment above) I was going to do /src/qfit and src/scripts. I would like the post analysis scripts

**Pull request closed without merging**
